## np.random.randint(low, high, size) 

In [118]:
import numpy as np

arr= np.random.randint(1,100, size=(10,5))  #here, 10 row (sample), 5 column (feature)

In [119]:
arr.shape

(10, 5)

In [120]:
b= arr.reshape(5,10) # age 10ta row,5at col celo. akn change kore 5ta row,10ta col korlm
b.shape
b.ndim
b 

array([[83, 98, 40, 81, 31, 11, 46, 96, 62, 45],
       [88, 89, 41, 19, 12, 24, 46, 46, 33, 92],
       [63, 52, 61, 64, 24, 81, 84, 23, 83,  7],
       [83, 47, 34, 94, 15, 55, 45, 47, 68,  3],
       [50, 15, 20, 83, 62, 37, 83, 37,  9, 61]], dtype=int32)

In [121]:
flatten= b.flatten()
print(flatten)
print(flatten.ndim) #1


column_wise_flattening= np.ravel(b, order= "F")
print(column_wise_flattening)

[83 98 40 81 31 11 46 96 62 45 88 89 41 19 12 24 46 46 33 92 63 52 61 64
 24 81 84 23 83  7 83 47 34 94 15 55 45 47 68  3 50 15 20 83 62 37 83 37
  9 61]
1
[83 88 63 83 50 98 89 52 47 15 40 41 61 34 20 81 19 64 94 83 31 12 24 15
 62 11 24 81 55 37 46 46 84 45 83 96 46 23 47 37 62 33 83 68  9 45 92  7
  3 61]


In [122]:
a = np.random.randint(1,10, size=(2,3))
b = np.random.randint(20,30, size=(2,3))
print(a)
print(b)

[[5 2 4]
 [3 8 2]]
[[29 20 22]
 [25 24 25]]


## Concatenate

In [123]:
con_row= np.concatenate((a,b), axis=0) #row wise
print(con_row)

con_col= np.concatenate((a,b), axis=1) #column wise
print(con_col)

[[ 5  2  4]
 [ 3  8  2]
 [29 20 22]
 [25 24 25]]
[[ 5  2  4 29 20 22]
 [ 3  8  2 25 24 25]]


In [124]:
#error
x = np.random.randint(1,10, size=(2,3))
y = np.random.randint(1,10, size=(1,3))

r= np.concatenate((x,y), axis=1)
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## Transpose 

In [125]:
mat= np.array([[10,20,30],
               [30,40,50]
              ])
transpose= mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [126]:
# array split
a = np.random.randint(1,10, size=(10,))
print(a)

splitted_array= np.array_split(a,3)
print(splitted_array)

# splitted_array= np.split(a,3) # split--> only for equal division
# print(splitted_array) #error

[7 3 4 5 8 6 1 5 8 5]
[array([7, 3, 4, 5], dtype=int32), array([8, 6, 1], dtype=int32), array([5, 8, 5], dtype=int32)]


## Arithmetic Operators and Mathematical function

In [127]:
#faster for vectoriszation

x= np.array([10,20,30,40])
y= np.array([2,3,4,5])
add= x+y
print(add)

sub= x-y
print(sub)

mul= x* y
print(mul)

div= x/y
print(div)

remainder= x% y
print(remainder)


[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [128]:
#mathematical function

#trigonometry
#sin, cos, tan takes values in radian

sin_val= np.sin(x)
print(sin_val)

cos_val= np.cos(x)
print(cos_val)

#radina to degree
deg_convert= np.rad2deg(x)
print(deg_convert)



[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [129]:
#log
base_10_log_val= np.log10(x)
print(base_10_log_val)


x=np.array([9,16,25,36])
two_diye_kotobar_bhag_korbo= np.log2(x)
print(two_diye_kotobar_bhag_korbo)

#square root
sqrt=np.sqrt(x)
print(sqrt)


[1.         1.30103    1.47712125 1.60205999]
[3.169925   4.         4.64385619 5.169925  ]
[3. 4. 5. 6.]


In [130]:
#Different

s= np.sum(x)
print(s)

#prefix sum
cumulative_sum= np.cumulative_sum(x)
print(cumulative_sum)

86
[ 9 25 50 86]


## Broadcasting

In [131]:
# x= np.array([10,8,16,100])
# result= x** 2
# print(result)

# result= x + 2
# print(result)

# result= x - 2
# print(result)

matrix= np.array([[10,20,30],
               [30,40,50]
              ])
result= matrix + 2
# print(result)


#vector
vector= np.array([1,2,3]) # col er size and vector er size must same hoya lagbe
result= matrix + vector
print(result)


[[11 22 33]
 [31 42 53]]


## Logical Function

In [132]:
#comparison --> > , < , <=, >=, ==, !=

x= np.array([10,8,16,100])
y= np.array([2,3,4,5])

greater_than = x>y
print(greater_than)

equal = x==y
print(equal)

#all ()-> check all are true
#any()-> je kono ekta true ache kina

print(np.all(greater_than))
print(np.any(equal))


[ True  True  True  True]
[False False False False]
True
False


## Sorting

In [133]:
#inplace
x= np.array([10,8,16,100])
z= x.copy()
print(z)

z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [134]:
#copy sorting
print(x)
sort_arr= np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [135]:
#2D array sorting

mat= np.array([[10,3,5], [8,4,9]])
#horizontal axis=1
hor_sort= np.sort(mat, axis=1)
print(hor_sort)


#verticals 
ver_sort= np.sort(mat, axis=0)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [136]:
print(x)

[ 10   8  16 100]


In [137]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index= np.where(x==16) # return index
print(index)

index= np.where(x>8,x,0) # return array
print(index)

(array([2]),)
[ 10   0  16 100]


In [138]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [139]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array 
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [140]:
print(x)
maximum_value_index= np.argmax(x)
print(maximum_value_index)
minimum_value_index= np.argmin(x)
print(minimum_value_index)

[ 10   8  16 100]
3
1


## Counting in ndarray

In [141]:
a= np.random.randint(1, 100, size=(100,))
print(a)





[72 40 33 35  9 28 46 80 60 56 89 61 87 99 38 46 86 27 69 41 19 85 61 35
 41 47 56 80  9 42 61  4 59 29 47 91 72 22 35 13 24 41 36  9 21 54 30 43
 33 45 76 85 93 34  1 55 38 82 85 17 42  1 66  3 51 53 60 79 56 71 95 85
 57 87 15 97  1 64 64 81 44 23 97 32 11 76 47 38  4 37 12 94 55 69 69 76
  6 54 43 85]


In [142]:
value_great_than_60 = np.count_nonzero(a>40)
print(value_great_than_60)

63


In [143]:
unique_values= np.unique(a)
print(a)

unique_values= np.unique(a, return_counts=True) # unique value koybar ache oitar array
print(unique_values)

[72 40 33 35  9 28 46 80 60 56 89 61 87 99 38 46 86 27 69 41 19 85 61 35
 41 47 56 80  9 42 61  4 59 29 47 91 72 22 35 13 24 41 36  9 21 54 30 43
 33 45 76 85 93 34  1 55 38 82 85 17 42  1 66  3 51 53 60 79 56 71 95 85
 57 87 15 97  1 64 64 81 44 23 97 32 11 76 47 38  4 37 12 94 55 69 69 76
  6 54 43 85]
(array([ 1,  3,  4,  6,  9, 11, 12, 13, 15, 17, 19, 21, 22, 23, 24, 27, 28,
       29, 30, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47,
       51, 53, 54, 55, 56, 57, 59, 60, 61, 64, 66, 69, 71, 72, 76, 79, 80,
       81, 82, 85, 86, 87, 89, 91, 93, 94, 95, 97, 99], dtype=int32), array([3, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       3, 1, 1, 3, 1, 3, 2, 2, 1, 1, 2, 3, 1, 1, 2, 2, 3, 1, 1, 2, 3, 2,
       1, 3, 1, 2, 3, 1, 2, 1, 1, 5, 1, 2, 1, 1, 1, 1, 1, 2, 1]))


## statistical function

In [154]:
#data loading

data = np.genfromtxt('Downloads/student_scores.csv', delimiter=',', skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [165]:
#statistics
math_marks= data[::, :1]
print(math_marks.T)

max_math_marks= np.max(math_marks)
print(max_math_marks)

min_math_marks= np.min(math_marks)
print(min_math_marks)

avg_math_marks= np.mean(math_marks)
print(avg_math_marks)

median_math_marks= np.median(math_marks)
print(median_math_marks)


#standard deviation
std_math_marks= np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


## linear algebra

In [168]:
study_hours= np.array([2,4,5,7,8])
exam_scores= np.array([65, 75, 78, 88, 92])
data= np.array([study_hours, exam_scores])
correlation= np.corrcoef(data)
print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


In [171]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

dot_product= np.dot(a,b)
print(dot_product)


# trace 
print(np.trace(b))


[[ 58  64]
 [139 154]]
17


In [173]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)


rank_sq = np.linalg.matrix_rank(sq_mat)
print(rank_sq)

0.0
2
