Email address:  mariamukti051@gmail.com

In [63]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# Ques -> 01

In [64]:
#age array er sob
age_array= np.array(ages)
print(age_array)
print(age_array.dtype)
print(age_array.ndim)
print(age_array.shape)
print(age_array.size)


#salarayr sob
salaries_array= np.array(salaries)
print(salaries_array)
print(salaries_array.dtype)
print(salaries_array.ndim)
print(salaries_array.shape)
print(salaries_array.size)

[56 46 32 25 38 56 36 40 28 28]
int64
1
(10,)
10
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10


# Ques -> 02

In [65]:
salaries_array= np.array(salaries)
print(salaries_array)

#high
highest_salary= np.max(salaries_array)
print(highest_salary)

#low
lowest_salary= np.min(salaries_array)
print(lowest_salary)


#avg salary
avg_salary= np.mean(salaries_array)
print(avg_salary)


#avg age
avg_age= np.mean(age_array)
print(avg_age)


[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
89735
30769
57446.9
38.5


# Ques -> 03

In [66]:
age_array= np.array(ages)
# print(age_array)
age_greater_than_30= age_array[age_array > 30]
print(age_greater_than_30)


coutn_older_thean_30= age_greater_than_30.size
print(coutn_older_thean_30)

[56 46 32 38 56 36 40]
7


# Ques -> 04

In [67]:
age_array= np.array(age)
# print(age_array)

age_after_5= age_array + 5
print(age_after_5)

[61 51 37 30 43 61 41 45 33 33]


# Ques-> 05

In [68]:
salaries_array= np.array(salaries)
# print(salaries_array)

total_salary= np.sum(salaries_array)
print(total_salary)

#diff
difference= np.max(salaries_array) - np.min(salaries_array)
print(difference)

574469
58966


# 2) Pandas

## Ques -> 06

In [69]:
import pandas as pd
df= pd.read_csv("employees.csv")
print(df)
# print(type(df))

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR


In [70]:
#display first 5 row
df.head(5)

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

In [71]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


In [72]:
#describe
df.describe()

id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

# Ques-> 07

In [73]:
df

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [74]:
print(df[['id', 'age', 'salary']])

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311


In [76]:
df.tail(3)

id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR

# Ques->08

In [75]:
df

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [50]:
IT_employee= df[df['dept']== 'IT']
print(IT_employee)

total_IT_employee= IT_employee.shape[0]
print(total_IT_employee)

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
3


# Ques -> 09

In [77]:
df

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [78]:
sorted_salary= df.sort_values(by= 'salary', ascending=False)
# print(sorted_salary)

top_3_highest_paid= sorted_salary.head(3)
print(top_3_highest_paid[['dept', 'age']])

      dept  age
6  Finance   36
7       IT   40
0       HR   56


# Ques->10

In [79]:
df

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [80]:
df.loc[df['salary']> 80000, 'salary']= 80000 #replace

new_avg_salaray= df['salary'].mean()
print(df['salary'].values)
new_avg_salary=df['salary'].mean()
print(new_avg_salary)

[77191 74131 46023 71090 31685 30769 80000 80000 32433 35311]
55863.3
