1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.


In [3]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print()

# 2D array
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]
                ])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print()

# 3D array
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3)
print(arr3.ndim)
print(arr3.shape)


[1 2 3 4 5]
1
(5,)

[[1 2 3]
 [4 5 6]]
2
(2, 3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


2 . Create:
an array of zeros of shape (3,3)
an array of ones of shape (2,5)
an array filled with 7

In [7]:
zeros_arr = np.zeros((3, 3))
print(zeros_arr)
print()

# Array of ones (2x5)
ones_arr = np.ones((2, 5))
print(ones_arr)
print()

# Array filled with 7
sevens_arr = np.full((3, 4), 7)
print(sevens_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


3 . Create an array of even numbers between 10 and 50 using arange.

In [8]:
# Create an array of even numbers between 10 and 50
even_arr = np.arange(10, 51, 2)
print(even_arr)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


4 . Create a 4×4 matrix from 0–15. Then , extract:
  -> the first row
  -> the last column
  -> a 2×2 subarray from the center


In [9]:
# Create a 4x4 matrix from 0 to 15
arr = np.arange(16).reshape(4, 4)
print(arr)
print()

# Extract the first row
first_row = arr[0, :]
print(first_row)
print()

# Extract the last column
last_column = arr[:, -1]
print(last_column)
print()

# Extract a 2x2 subarray from the center
center_subarray = arr[1:3, 1:3]
print(center_subarray)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[0 1 2 3]

[ 3  7 11 15]

[[ 5  6]
 [ 9 10]]


5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [10]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# 1D array
arr = np.array([1, 2, 3])

# Add the 1D array to each row of the matrix
result = matrix + arr

print(matrix)
print(arr)
print(result)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[1 2 3]
[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [ ]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

# (A + B) / 2
avg = (A + B) / 2
print("(A + B) / 2 :\n", avg)

# A**2 + B**2
sum_of_squares = A**2 + B**2
print("\nA**2 + B**2 :\n", sum_of_squares)
