In [5]:
arr= [1,2,3]
print(arr * 5)

arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [7]:
import numpy as np 

arr1 = np.array([1,2,3]) 

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


## Ndarray


In [13]:
import numpy as np

#1D array
arr1=np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)



#2D array
arr2=np.array([[1,2,3], #row 1 
               [4,5,6]]) #row 2
print(arr2.ndim)



#3D array
arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 
    
    #2nd floor
     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2  
  
])
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


##Array Attributes

In [17]:
#dimention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#Shape
print(arr1.shape)      
print(arr2.shape)   
print(arr3.shape)   

#Data type
print(arr1.dtype)      
print(arr2.dtype)   
print(arr3.dtype) 


#Size
print(arr1.size)      
print(arr2.size)   
print(arr3.size) 

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


##ndarray data type

In [22]:
arr=np.array([1,2,3])
print(arr.dtype)

arr=np.array([1.4,2.6,3.98])
print(arr.dtype)

int64
float64


In [23]:
arr=np.array([1,2,3.98])
print(arr.dtype) #upcasted to float

#upcasted to string
arr=np.array([1.4,2.6,'3'])
print(arr.dtype)

float64
<U32


### selecting data type for an array

In [32]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)


arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

## ndarray creation from existing data

In [40]:
#List
lst=[10,20,30,40,40.5]
arr= np.array(lst, dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)


#MI
mixed_lst=[10,True,"hello"]
arr= np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)


#using matrix
matrix= [ [1,2,3],
         [4,5,6]
        ]
arr= np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'hello']
<class 'numpy.ndarray'>
<U21
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [51]:
#dictionary

dic={'a' :10, 'b' : 20, 'c': 30}
print(type(dic))

keys=dic.keys()
print(keys)
values=dic.values()
print(values)
itmes=dic.items()
print(itmes)

#Keys to ndarray
arr=np.array(list(keys))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

<class 'dict'>
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [53]:
#values to ndarray
arr=np.array(list(values))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [57]:
#items to ndarray
arr=np.array(list(itmes))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## Creating ndarray from scratch

In [61]:
#np.zeros
arr=np.zeros((2,3), dtype=np.int8)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [64]:
#np.ones
arr = np.ones((3,4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [65]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

[[97  0  0]
 [ 0 98  0]
 [ 0  0 99]
 [ 0  0  0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [68]:
#np.full 

arr = np.full((4,3),np.inf)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64) 

print(arr)
print(arr.shape)
print(arr.dtype)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


### array creation with random values

In [71]:
#np.random.rand(shape)

arr = np.random.rand(2,3) 

print(arr)
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.63309815 0.27099776 0.60239094]
 [0.44815907 0.29372365 0.76932601]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [72]:
# np.random.randint(start,end, shape) 

arr = np.random.randint(1,10 , (2,3))  

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[4 8 8]
 [2 4 4]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [73]:
# np.random.uniform(start,end, shape) 

arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[[53.62160288 63.83782671 57.70299922 50.79303333]
  [88.69094638 62.58805035 80.14773051 98.96571316]
  [64.48795534 53.98823638 64.39563707 91.77073034]]

 [[96.20572073 53.82001901 84.63075359 71.61155038]
  [79.90538831 98.72562248 78.84413841 62.08535522]
  [61.58387475 99.45792485 72.12209227 53.25684571]]

 [[67.00986301 78.17627326 57.91058186 55.78365494]
  [90.22686341 63.79461565 92.70000438 95.35803592]
  [65.96781877 81.89163421 94.06342513 89.65897553]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


### array creation with range functions

In [74]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 

print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [77]:
# np.linspace(start , end(included) , koita point ) 

arr = np.linspace(0, 4 ,6)


print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [78]:
# np.logspace(start , end(included) , koita ) 

arr = np.logspace(0 , 4 ,6, base =2) 

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## creating matrix for Linear algebra

In [81]:
diagonal_matrix= np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [88]:
#identity matrix

identity_mat= np.eye(5)
print(identity_mat)
print(identity_mat.shape)


#np.eye(row, col)
mat= np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## indexing and slicing

In [94]:
## indexing
print(arr1)
print(arr2)

print(arr1[2]) # 2
arr1[2]=100
print(arr1)

#2D ->  [1 2 3]
 #     [4 5 6]

print(arr2[0][2])
arr2[0][2]=100
print(arr2)

[  1   2 100   4   5]
[[1 2 3]
 [4 5 6]]
100
[  1   2 100   4   5]
3
[[  1   2 100]
 [  4   5   6]]


In [98]:
#slicing 
#1d = arr[start:end:step] 

arr1_mod = arr1[1:4]

print(arr1_mod)

[  2 100   4]


In [109]:
#2D
# arr[row start : row end : step , col start : col end : step]

# print(arr2)
#getting a row
row_0= arr2[0:1, ]
print(row_0)


row_1= arr2[1: , ]
print(row_1)


#getting a column
col_0= arr2[:: , 0:1] ## value pass na korle :: dibo
print(col_0)

col_1= arr2[:: , 1:2]
print(col_1)



# getting a portion
portion= arr2[:: , 0:2]
print(portion)

[[  1   2 100]]
[[4 5 6]]
[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


## Advanced Indexing

In [124]:
lst = np.array([ 10 , 20 ,30 ,40 ]) 
values= lst[[2,3]]
print(values) ## [30 40]

values = lst[[0,3,1]] ##[10 40 20]

print(values)

[30 40]
[10 40 20]


In [116]:
print(arr2)

print(arr2[[0,1],[1,2]])


#boolean kono kichu diye
print(arr2[arr2>2])

arr2[arr2>2]=0
print(arr2)

[[  1   2 100]
 [  4   5   6]]
[2 6]
[100   4   5   6]
[[1 2 0]
 [0 0 0]]


In [117]:
print(arr2)

[[1 2 0]
 [0 0 0]]


In [123]:
arr=np.array([[10,20,30], [100,200,300]])
print(arr)

#iteration
for i in np.nditer(arr):
    print(i)

[[ 10  20  30]
 [100 200 300]]
10
20
30
100
200
300
